server:
    port: 8081

external-server:
    metadata:
        url: http://localhost:8088


spring:
    datasource:
        jdbc-url: jdbc:mysql://localhost:3306/campus?serverTimezone=Asia/Seoul
        username: myuser
        password: mypassword
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                hbm2ddl:
                    auto: validate
    data:
        mongodb:
            uri: mongodb://rootuser:1234@localhost:27017/campus?authSource=admin
        redis:
            host: localhost
            port: 6379
        elasticsearch:
            host: localhost
            port: 9200

    kafka:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094